# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run Newman htmlextra image
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          docker container run -t -v $(pwd):/etc/newman dannydainton/htmlextra \
          run 'jornadacolaborativa.postman_collection.json' \
          -k \
          -r cli,htmlextra \
          --reporter-htmlextra-export /etc/newman/index.html \
          --reporter-htmlextra-browserTitle "Jornada Colaborativa" \
          --reporter-htmlextra-title "Jornada Colaborativa - Nomes Mais Comuns No Brasil"

      # Show the directory and list its contents
      - name: Run a single-line script
        run:  ls -lathr
